[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-rt = "2.10.0"
actix-web = "4.0"
rand = "0.9.0"
rsa = { version = "0.9.8", features = ["pem"] }
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10.8"

[[bin]]
name = "backend"
path = "main.rs"
